#!/bin/bash
set -e

# DEVONThink Templates
if [ ! -d ~/Library/Application\ Support/DEVONthink\ Pro\ 2/Templates.noindex ]; then
    echo "Creating DEVONThink User directory"
    mkdir -p ~/Library/Application\ Support/DEVONthink\ Pro\ 2/Templates.noindex
fi

echo "Linking DEVONThink profile"
ln -sf ~/Library/Mobile\ Documents/com\~apple\~CloudDocs/Settings/DEVONThink/_My\ Templates ~/Library/Application\ Support/DEVONthink\ Pro\ 2/Templates.noindex/_My\ Templates

# remove the not-signed message from the Finder Preview plugins
echo Remove the not-signed message from the Finder preview plugins
xattr -cr ~/Library/QuickLook/*.qlgenerator
qlmanage -r
qlmanage -r cache
defaults write com.whomwah.quicklookstephen maxFileSize 102400
