#!/bin/bash
set -e

# DEVONThink Templates
if [ ! -d ~/Library/Application\ Support/DEVONthink\ Pro\ 2/Templates.noindex ]; then
    echo "Creating DEVONThink User directory"
    mkdir -p ~/Library/Application\ Support/DEVONthink\ Pro\ 2/Templates.noindex
fi

echo "Linking DEVONThink profile"
ln -sf ~/Library/Mobile\ Documents/com\~apple\~CloudDocs/Settings/DEVONThink/_My\ Templates ~/Library/Application\ Support/DEVONthink\ Pro\ 2/Templates.noindex/_My\ Templates
