#!/bin/bash
set -e

if ! [ -L ~/.gnupg ] || ! [ -L ~/.ssh ]
then
  echo "Run script/setup first!" >&2
  exit 1
fi

onepassword_login() {
  if ! command -v op >/dev/null
  then
    brew cask install 1password-cli
  fi

  # shellcheck disable=SC2154
  if [ -z "$OP_SESSION_mcquaid" ]
  then
    echo "Logging into 1Password..."
    eval "$(op signin my.1password.com mail@sascha-kiefer.de)"
  fi
}

onepassword_get() {
  if [ -f "$HOME/$2" ]
  then
    echo "$2 already exists."
    return
  fi
  echo "Extracting $2..."
  onepassword_login
  op get document "$1" > "$HOME/$2"
  chmod 600 "$HOME/$2"
}

onepassword_get cmzwzul3lvd4xj4kogarpr7lli .ssh/id_rsa.pub
onepassword_get punhtierbffphfh6halzvsnnwu .ssh/id_rsa

if ! [ -f "$HOME/.secrets" ]
then
  echo "Extracting secrets..."
  if ! command -v jq >/dev/null
  then
    brew install jq
  fi
  onepassword_login
  BINTRAY_KEY=$(op get item t6wkb3pguncltiehjfoeft3r6q | jq -r '.details.sections[1].fields[].v')
  GITHUB_TOKEN=$(op get item g6klazxi3ffprbnou2mexznlay | jq -r '.details.sections[1].fields[].v')
  cat > "$HOME/.secrets" <<EOF
export BINTRAY_KEY=$BINTRAY_KEY
export GITHUB_TOKEN=$GITHUB_TOKEN
EOF
  chmod 600 "$HOME/.secrets"
fi

echo "Storing SSH keys in keychain..."
ssh-add -K